name: Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: yarn install

    - name: Test
      run: yarn test

    - name: Build
      run: yarn build

    - name: Deploy to Production
      run: | 
          yarn global add serverless
          serverless deploy --stage prod
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
